POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker 2"
}

###

GET http://localhost:3333/courses

### 

GET http://localhost:3333/courses/7537efa1-b0bc-4144-ab4c-b74bb7b78a77